if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

const express = require("express");
const sequelize = require("./database");

// initializing model definitions
require("./models");

// fetching defined models
const User = sequelize.model("User");

// config vars
const PORT = process.env.PORT | 8000;
const HOST = "192.168.0.100"; // const HOST = process.env.HOST | '192.168.0.100'

const app = express();

// app.use(express.urlencoded({ extended: true }))
app.use(express.json());

app.use((req, res) => {
  res.send({ message: "testing successful." });
});

app.listen(PORT, HOST, async () => {
  console.log(`server connected to http://${HOST}:${PORT}`);

  try {
    await sequelize.sync({
      // alter: true,
      force: true,
    });

    // Simple INSERT queries
    const jane = await User.create({ name: "Jane", age: 23 });
    console.log(`Jane's autogenerated id: ${jane.id}`);

    // specifying which attributes to set in create method
    const user = await User.create(
      {
        username: "user123",
        isAdmin: true,
      },
      { fields: ["username"] }
    );
    await user.reload();
    console.log({ name: user.username, isAdmin: user.isAdmin });
  } catch (e) {
    console.log({ e });
  }
});
